Удален временный текст
htmlacademy-htmlcss/1529381-nerds-29 pull request #2
Opened 2020-09-29 17:32 UTC by ichekurova

2020-10-12 18:22 UTC, costigans requested changes

2020-10-14 11:05 UTC, costigans requested changes

2020-10-14 11:05 UTC, costigans commented on index.html
> +    <div>
Всё ещё нет заголовка.
И ссылки с логотипами можно обернуть в список

2020-10-14 11:05 UTC, costigans commented on index.html
> +          <h2>Долго, дорого, скрупулезно</h2>
Не `h2`, просто `p`

2020-10-14 11:05 UTC, costigans commented on index.html
> +        <dd>Уровень самоотдачи</dd>
Поменять местами

2020-10-14 11:05 UTC, costigans commented on index.html
> +        <dd>Уровень самоотдачи</dd>
`Параметр: занчение`

2020-10-14 11:36 UTC, ichekurova commented on index.html
> +          <h2>Долго, дорого, скрупулезно</h2>
"Всё ещё нет заголовка." - Имеется в виду заголовок с партнёрами?

2020-10-14 14:39 UTC, merged